# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bfcea5aeec8a73dca89dc4d52c351241ce6bec41e418998b7a9ac22961f634273e22c3745645c3c9dcd385c4350bb57fdf0ce570d86b7966d1bb0c5ffe09cbf5

test:
  secret_key_base: 63153da7041af17984df6147a22e3b8988873f75e9dfe13447038e6c7fd853f176dc9595c449aa09b3bf4e47219f2629bfbab9be201d9e82b30ec6d49cc9c3a1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
